---
name: CD

on:
  push:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Plan
    uses: luisdibdin/aws-terraform/.github/workflows/terraform-plan.yaml@main
    with:
      environment: dev
      upload-plan: true
    secrets:
      TERRAFORM_PLAN_ROLE_ARN: ${{ secrets[format('TERRAFORM_PLAN_ROLE_ARN_DEV' )] }}
  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    if: ${{ needs.terraform-plan.outputs.tfplan-diff == 'true' }}
    uses: luisdibdin/aws-terraform/.github/workflows/terraform-apply.yaml@main
    with:
      environment: dev
    secrets:
      inherit
      
  