---
name: CI

on:
  pull_request:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform Plan
    uses: luisdibdin/aws-terraform/.github/workflows/terraform-plan.yaml@lambda-layer
    secrets:
      OICD_READ_ONLY_IAM_ROLE_ARN: ${{ secrets.TERRAFORM_PLAN_ROLE_ARN }}