---
name: CI

on:
  pull_request:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Plan
    uses: luisdibdin/aws-terraform/.github/workflows/terraform-plan.yaml@test-workflow
    secrets:
      inherit