---
name: CI

on:
  pull_request:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform-plan:
    strategy:
      matrix:
        environment: [dev, prod]
    name: Terraform Plan
    uses: luisdibdin/aws-terraform/.github/workflows/terraform-plan.yaml@main
    with:
      environment: ${{ matrix.environment }}
    secrets:
      TERRAFORM_PLAN_ROLE_ARN: ${{ secrets[format('TERRAFORM_PLAN_ROLE_ARN_{0}', matrix.environment )] }}
